### PR TITLE
Closes #2521 - Fix code smells Stream.collect(Collectors.toList()) to…

### LINKED ISSUE #2521: Fix code smells

### PR DESCRIPTION
**Pull request by MM1277**
… Stream.toList()

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #&lt;Issue Number&gt;: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java [hunk 1]
```diff
@@ -136,6 +136,7 @@ public class TaskanaConfiguration {
 
   // region custom configuration
   private final Map<String, String> properties;
+
```
Comment (ryzheboka) [inline lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java:139]: Why did you add newlines to this class?

**Review by ryzheboka — CHANGES_REQUESTED** [review]

**Review by ryzheboka — APPROVED** [review]
