### PR TITLE
Closes #2459: Fix Code Smells

### LINKED ISSUE #2459: Resolve Code Smells from SonarCloud

### PR DESCRIPTION
**Pull request by jamesrdi**
https://sonarcloud.io/summary/new_code?id=jamesrdi_taskana&branch=TSK-2459

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #&lt;Issue Number&gt;: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java [hunk 1]
```diff
@@ -64,9 +64,9 @@ public boolean run() throws SQLException {
     }
     if (LOGGER.isDebugEnabled()) {
       LOGGER.debug(outWriter.toString());
-    }
-    if (!errorWriter.toString().trim().isEmpty()) {
-      LOGGER.error(errorWriter.toString());
+      if (!errorWriter.toString().trim().isEmpty()) {
```
Comment (ryzheboka) [inline common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java:67]: Why is this only relevant when debugging?

Comment (jamesrdi) [reply common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java:67]: You are right, I will change it back

**Review by ryzheboka — APPROVED** [review]
