### PR TITLE
Closes #2184 - fix setting ownerLongName during claim

### LINKED ISSUE #2184: Fix getting additional user info from claim
Now, if claim is executed with additionalUserInfo, the user info table can't be found. The method Claim in TaskServiceImpl needs to be fixed.

Todo: 
OwnerLongName should be filled out after a connection to the database has been opened. Move setting ownerLongName, so that it's done after a connection to the database has been opened.

### PR DESCRIPTION
**Pull request by ryzheboka**
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2184

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java [hunk 1]
```diff
@@ -394,4 +409,40 @@ void should_ForceCancelClaimTask_When_InReviewByAnotherUser() throws Exception {
...
+    @TaskanaInject TaskService taskService;
+
+    @Override
+    public TaskanaConfiguration.Builder modify(TaskanaConfiguration.Builder builder) {
+      return builder.addAdditionalUserInfo(true);
+    }
+
+    @WithAccessId(user = "user-1-2")
+    @Test
+    void should_SetOwnerLongName() throws Exception {
```
Comment (gitgoodjhe) [inline lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java:426]: shoudl we add a "when" clause to the test name? like should_SetOwnerLongName_When_AdditionalUserInfoEnabled() or soemthing like that?

**Review by gitgoodjhe — CHANGES_REQUESTED** [review]

File: lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java (hunk 1 above)
Comment (gitgoodjhe) [reply lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java:426]: Oh I didn't see that it was in that nested class...or rather Github doesnt show it in the lines changed...I think this is fine then the way it is

**Review by gitgoodjhe — APPROVED** [review]
