### PR TITLE
Closes #2634: Clear cache of SQL session from TaskanaEngine

### LINKED ISSUE #2634: Read Task after Update Task from a ReviewRequired SPI gives stale data
Steps to reproduce the problem:
- Implement the SPI ReviewRequiredProvider in the module taskana-rest-spring-example-boot
- Put a break point in the reviewRequired method to stop the execution
- Start 2 instances of taskana-rest-spring-example-boot using PostgreSQL
- Open the GUI, select a task to complete it: the break point should kick in
- While the execution of one instance is paused, call the update task endpoint on the other instance (e.g. PUT http://localhost:8081/taskana/api/v1/tasks/:taskId) and change a custom field
- Using another break point, check the output of getTask() in TaskServiceImpl.requestReview: the changes in the custom field from the update in the previous point should not be there

### PR DESCRIPTION
**Pull request by CRoberto1926**
Steps to reproduce the problem described in #2634:
- Implement the SPI ReviewRequiredProvider in the module taskana-rest-spring-example-boot
- Put a break point in the reviewRequired method to stop the execution
- Start 2 instances of taskana-rest-spring-example-boot using PostgreSQL
- Open the GUI, select a task to complete it: the break point should kick in
- While the execution of one instance is paused, call the update task endpoint on the other instance (e.g. PUT http://localhost:8081/taskana/api/v1/tasks/:taskId) and change a custom field
- Using another break point, check the output of getTask() in TaskServiceImpl.requestReview: without the changes in this PR, the changes in the custom field from the update in the previous point should not be there

The explanation is that this last getTask() is returning cached data from the local SQL session.

By calling the new TaskanaEngine API method implemented in this PR from the SPI ReviewRequiredProvider, the cache is cleared and the last getTask() above returns fresh data from DB.

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #&lt;Issue Number&gt;: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: lib/taskana-core/src/main/java/pro/taskana/common/api/TaskanaEngine.java [hunk 1]
```diff
@@ -226,6 +226,9 @@ default void runAsAdmin(Runnable runnable) {
    */
   CurrentUserContext getCurrentUserContext();
 
+  /** Clears the cache of the underlying local SQL session. */
+  void clearSessionCache();
```
Comment (CRoberto1926) [inline lib/taskana-core/src/main/java/pro/taskana/common/api/TaskanaEngine.java:230]: Rename to clearSqlSessionCache

**Review by holgerhagen — APPROVED** [review]
