### PR TITLE
Closes #2289 - fix Sonarcloud vulnerabilities and bugs

### LINKED ISSUE #2289: Remove Bugs and Vulnerabilities recognized by Sonarcloud
https://sonarcloud.io/project/overview?id=Taskana_taskana

### PR DESCRIPTION
**Pull request by ryzheboka**
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2289

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → (Closes) #<Issue Number>: Your commit message. i.e. Closes #2271: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/assembler/ReportRepresentationModelAssembler.java [hunk 1]
```diff
@@ -138,11 +138,11 @@ public ReportRepresentationModel toModel(
 
   @NonNull
   public ReportRepresentationModel toModel(
-      @NonNull TaskStatusReport report,
-      @NonNull List<String> domain,
-      @NonNull List<TaskState> state,
-      @NonNull List<String> workbasketIds,
-      @NonNull Integer priorityMinimum)
+      TaskStatusReport report,
```
Comment (ryzheboka) [inline rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/assembler/ReportRepresentationModelAssembler.java:141]: @mustaphazorgati what do you think about removing the @NotNull annotation? Currently, this toModel is called in a way that the parameters can be null. Sonarcloud sees this as bug. That's why the annotation doesn't seem to br correct to me. Is there a reason for this annotation? Is it an ok solution to just remove the annotation?
