### PR TITLE
Closes #2162 - forceCancelClaim does not throw InvalidOwnerException

### LINKED ISSUE #2162: Surround NotAuthorizedException with try catch in the force-methods of TaskService
At the moment, NotAuthorizedException is in the method signature of force methods in TaskService. However, it should not be thrown there. Please surround the corresponding code with try .. catch like in the picture (but without :D).

forceMethodsRewriteNewTicket

### PR DESCRIPTION
**Pull request by Lnrivas**
Added code to TaskServiceImpl.java forceCancelClaim to fix issue #2162: "Surround NotAuthorizedException with try catch in the force-methods of TaskService." 

---
Release Notes:

```

```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java [hunk 1]
```diff
@@ -236,8 +236,14 @@ Task cancelClaim(String taskId)
...
-          NotAuthorizedOnWorkbasketException,
-          InvalidTaskStateException;
+          InvalidTaskStateException {
+      try {
+        return this.cancelClaim(taskId, true);
+      } catch (NotAuthorizedOnWorkbasketException e) {
+        throw new SystemException(
+        "this should not have happened. You've discovered a new bug! :D", e); 
+      }
+    }
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java:246]: You have to do this in `TaskServiceImpl#forceCancelClaim` ;) 

Please also remove the NotAuthorizedOnWorkbasketException from this interface method.

**Review by mustaphazorgati — CHANGES_REQUESTED** [review]
Hey @Lnrivas!

Thanks for your contribution. Unfortunately the pipeline is broken. Can you fix it please? I'd be glad to integrate this PR.

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java (hunk 1 above)
Comment (Lnrivas) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java]: Sorry for the confusion @mustaphazorgati , I returned the file I edited back to the original form and added my changes to the file you mentioned: TaskServiceImpl.java

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java [hunk 2]
```diff
@@ -185,10 +185,14 @@ public Task cancelClaim(String taskId)
...
-          NotAuthorizedOnWorkbasketException,
-          InvalidTaskStateException {
-    return this.cancelClaim(taskId, true);
+          InvalidTaskStateException,
+          InvalidOwnerException
+      try {
+          return this.cancelClaim(taskId, true);
+      } catch (NotAuthorizedOnWorkbasketException e) {
+          throw new SystemException(
+            "this should not have happened. You've discovered a new bug! :D", e);
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:194]:
```suggestion
            "this should not have happened. You've discovered a new bug!", e);
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java [hunk 3]
```diff
@@ -185,10 +185,14 @@ public Task cancelClaim(String taskId)
   @Override
   public Task forceCancelClaim(String taskId)
       throws TaskNotFoundException,
-          InvalidOwnerException,
-          NotAuthorizedOnWorkbasketException,
-          InvalidTaskStateException {
-    return this.cancelClaim(taskId, true);
+          InvalidTaskStateException,
+          InvalidOwnerException
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:189]: Please remove the `NotAuthorizedOnWorkbasketException` in the interface method

**Review by mustaphazorgati — CHANGES_REQUESTED** [review]

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java (hunk 1 above)
Comment (mustaphazorgati) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java]: No worries mate! :) That's what PRs are for

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java (hunk 3 above)
Comment (Lnrivas) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:189]: Thanks for all the guidance! If I understand correctly, it is removed now.

Comment (mustaphazorgati) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:189]: Somewhat. The Pipeline will fail since you forgot to remove the JavaDoc entry for that exception 😉 

Other then that it looks fine :)

Comment (Lnrivas) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:189]: Ah yes, good catch, thanks

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java [hunk 4]
```diff
@@ -230,13 +230,11 @@ Task cancelClaim(String taskId)
    * @throws InvalidTaskStateException if the {@linkplain Task} is already in one of the {@linkplain
    *     TaskState#END_STATES}
    * @throws InvalidOwnerException cannot be thrown
-   * @throws NotAuthorizedOnWorkbasketException if the current user has no {@linkplain
    *     WorkbasketPermission#READ} for the {@linkplain Workbasket} the {@linkplain Task} is in
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java:233]:
```suggestion
```

**Review by mustaphazorgati — CHANGES_REQUESTED** [review]

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java [hunk 5]
```diff
@@ -185,10 +185,14 @@ public Task cancelClaim(String taskId)
...
+      try {
+          return this.cancelClaim(taskId, true);
+      } catch (NotAuthorizedOnWorkbasketException e) {
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:192]:
```suggestion
      } catch (InvalidOwnerException e) {
```

**Review by mustaphazorgati — CHANGES_REQUESTED** [review]

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (Lnrivas) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java]: No problem!

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java [hunk 6]
```diff
@@ -185,10 +185,14 @@ public Task cancelClaim(String taskId)
...
-    return this.cancelClaim(taskId, true);
+          InvalidTaskStateException,
+          InvalidOwnerException
+      try {
+          return this.cancelClaim(taskId, true);
+      } catch (InvalidOwnerException e) {
+          throw new SystemException(
+            "this should not have happened. You've discovered a new bug!", e);
+      }
   }
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java:196]: This is not compiling. Did you properly set up your dev environment?
It should look like this:
```
  @Override
  public Task forceCancelClaim(String taskId)
      throws TaskNotFoundException, InvalidTaskStateException, NotAuthorizedOnWorkbasketException {
    try {
      return this.cancelClaim(taskId, true);
    } catch (InvalidOwnerException e) {
      throw new SystemException("this should not have happened. You've discovered a new bug!", e);
    }
  }
```

**Review by mustaphazorgati — DISMISSED** [review]

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java (hunk 6 above)
Comment (Lnrivas) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java]: Not sure, I downloaded the repo but when compiling always get many many errors so I must be doing something wrong. I changed the code to look exactly as you suggested. Let me know if it still is not working on your end.

Comment (arolfes) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java]: Pipeline is working correctly now :-) thank you

**Comment by Lnrivas** [comment]
Fixed "this branch is out-of-date with the base branch" error and should be all good to go now. Thanks for all the help everyone, excited to have my first contribution be successfully merged as soon as possible :)

**Review by arolfes — APPROVED** [review]
