### PR TITLE
Closes #2246 - add grouping by sors and pors

### LINKED ISSUE #2246: Add aggregation by primary and secondary ObjectReferences
For primary ObjectReferences, following logic needs to be implemented: When using groupByPor, Tasks with the same por value should not be returned. Instead, only one Task should be returned for each por value. Additionaly, each Task should have a number of Tasks with the same por value attached

For secondary ObjectReferences, following logic needs to be implemented: When using groupBySor, you need to specify the type. Then, Tasks with the same value of the sor with the specified type are aggregated in the same way as decribed above. 

The specified functionality will only be added to the commonQuery. That's why an additional parameter is needed. This parameter will specify if the commonQuery will be used at all times, so that the db2 query will not be used at all.

Todos:

- Extend the Task entity by additional field groupByCount and initialize this field with zero
- Add groupBySor(type) and groupByPor() to the query
- Write tests
- Add the configuration parameter taskana.commonQueryUsage.enforce that forces to use commonQuery when running on db2
  => Needs to stay compatible, so that this parameter needs a correct default value
- Extend tests by this parameter
- Add rest parameters group-by with the parameter POR_VALUE (Enum value)  and group-by-sor with the type as parameter
- Add exception for incorrect use of group-by(POR_VALUE) 
- Write REST tests

### PR DESCRIPTION
**Pull request by ryzheboka**
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2246

---
Release Notes:

```
Add grouping by the same por or sor value. In case of sor values, a type needs to be specified. 
```
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [ ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] After integration of the PR, I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review
- [ ] After integration of the pull request, I verified our [bluemix test environment](http://taskana.mybluemix.net/taskana) is not broken

### Verified by the reviewer:
- [ ] Commit message format → TSK-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

File: lib/taskana-core/src/main/java/pro/taskana/task/api/models/TaskSummary.java [hunk 1]
```diff
@@ -80,6 +80,8 @@ public interface TaskSummary {
    */
   Instant getReceived();
 
+  Integer getGroupByCount();
```
Comment (arolfes) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/models/TaskSummary.java:83]: Please add a meaningful javadoc comment

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java [hunk 2]
```diff
@@ -1220,6 +1220,10 @@ public interface TaskQuery extends BaseQuery<TaskSummary, TaskQueryColumnName> {
   // endregion
   // region read
 
+  TaskQuery groupByPor();
```
Comment (arolfes) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1223]: Please add a meaningful javadoc comment

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java [hunk 3]
```diff
@@ -1220,6 +1220,10 @@ public interface TaskQuery extends BaseQuery<TaskSummary, TaskQueryColumnName> {
...
+
+  TaskQuery groupBySor(String type);
```
Comment (arolfes) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1225]: Please add a meaningful javadoc comment

File: lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java [hunk 4]
```diff
@@ -743,6 +757,11 @@ public static class Builder {
     private Set<WorkbasketPermission> minimalPermissionsToAssignDomains = new HashSet<>();
     // endregion
 
+    // region database configuration
+    @TaskanaProperty("taskana.feature.useSpecificDb2Taskquery")
+    private boolean useSpecificDb2Taskquery = false;
```
Comment (arolfes) [inline lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java:762]: Didn't we say the default is the old special DB2 query ? If yes, shouldn't the default be true?

**Review by arolfes — CHANGES_REQUESTED** [review]

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java [hunk 5]
```diff
@@ -68,7 +68,8 @@ public class TaskQueryImpl implements TaskQuery {
   private boolean addAttachmentClassificationNameToSelectClauseForOrdering = false;
   private boolean addWorkbasketNameToSelectClauseForOrdering = false;
   private boolean joinWithUserInfo;
-
+  private boolean groupByPor;
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:72]: This field is only used in TaskQuerySqlProvider. There, the variable name is specified as a String so that MyBatis can access it. However, Sonarcloud sees it as "unused", because it doesn't recognize the reference to the variable because it's in a String. How can I fix it?

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java [hunk 6]
```diff
@@ -68,7 +68,8 @@ public class TaskQueryImpl implements TaskQuery {
...
+  private String groupBySor;
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:73]: This field is only used in TaskQuerySqlProvider. There, the variable name is specified as a String so that MyBatis can access it. However, Sonarcloud sees it as "unused", because it doesn't recognize the reference to the variable because it's in a String. How can I fix it?

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskImpl.java [hunk 7]
```diff
@@ -25,14 +25,17 @@ public class TaskImpl extends TaskSummaryImpl implements Task {
   private CallbackState callbackState;
   private List<Attachment> attachments = new ArrayList<>();
 
-  public TaskImpl() {}
+  public TaskImpl() {
+    this.groupByCount = 0;
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskImpl.java]: I removed this.groupByCount = 0; from the constructor because it's unnecessary

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java [hunk 8]
```diff
@@ -0,0 +1,237 @@
...
+import pro.taskana.testapi.builder.TaskBuilder;
+import pro.taskana.testapi.builder.WorkbasketAccessItemBuilder;
+import pro.taskana.testapi.security.WithAccessId;
+import pro.taskana.workbasket.api.WorkbasketPermission;
+import pro.taskana.workbasket.api.WorkbasketService;
+import pro.taskana.workbasket.api.models.WorkbasketSummary;
+
+@TaskanaIntegrationTest
+public class TaskQueryImplGroupByAccTest {
+  @Nested
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java]: It's here by mistake. I adjusted it so it's not nested anymore.

File: lib/taskana-core/src/main/java/pro/taskana/task/api/models/TaskSummary.java (hunk 1 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/models/TaskSummary.java:91]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java (hunk 2 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1230]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java (hunk 3 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1241]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java (hunk 4 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java]: Yes, I inverted all values if this parameter.

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (arolfes) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:72]: OK, didn't realize that it is used by MyBatis...


Can you try what sonarcloud says when you add this annotation:
`@SuppressWarnings("unused")`

If this doesn't help, we ignore this code smell

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (arolfes) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:73]: OK, didn't realize that it is used by MyBatis...


Can you try what sonarcloud says when you add this annotation:
`@SuppressWarnings("unused")`

If this doesn't help, we ignore this code smell

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java [hunk 9]
```diff
@@ -1985,7 +2025,8 @@ public List<String> listValues(TaskQueryColumnName columnName, SortDirection sor
     try {
       taskanaEngine.openConnection();
       this.columnName = columnName;
-      this.orderBy.clear();
+      this.orderByOuter.clear();
+      this.orderByInner.clear();
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:2029]: Is this bevahiour documented?
e.g. someone could save the TaskQuery and execute 2 calls (listValues and list) and this behaviour would reset both order statements.

Either document that or restore the values after the data was fetched (and test that)

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java [hunk 10]
```diff
@@ -2237,7 +2283,12 @@ private TaskQuery addOrderCriteria(String columnName, SortDirection sortDirectio
     if (sortDirection == null) {
       sortDirection = SortDirection.ASCENDING;
     }
-    orderBy.add(columnName + " " + sortDirection);
+    orderByInner.add(columnName + " " + sortDirection);
+    if (columnName.startsWith("a") || columnName.startsWith("w") || columnName.startsWith("c")) {
+      orderByOuter.add(columnName.replace(".", "").toUpperCase() + " " + sortDirection);
+    } else {
+      orderByOuter.add(columnName + " " + sortDirection);
+    }
```
Comment (mustaphazorgati) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:2291]: Please comment this (and why it is necessary). It might be confusing for future devs. Fixing this would overload this ticket. Therefore, a comment is enough for me :)

File: lib/taskana-test-api/src/test/java/pro/taskana/testapi/builder/TaskBuilderTest.java [hunk 11]
```diff
@@ -212,7 +212,7 @@ void should_PopulateTask_When_UsingEveryBuilderFunction() throws Exception {
     expectedTask.setCallbackState(CallbackState.CALLBACK_PROCESSING_COMPLETED);
 
     assertThat(task)
-        .hasNoNullFieldsOrPropertiesExcept("ownerLongName")
+        .hasNoNullFieldsOrPropertiesExcept("ownerLongName", "groupByCount")
```
Comment (mustaphazorgati) [inline lib/taskana-test-api/src/test/java/pro/taskana/testapi/builder/TaskBuilderTest.java:215]: Please test that setting groupByCount works. This is a dirty workaround

**Review by mustaphazorgati — CHANGES_REQUESTED** [review]
This is just a partial. I didn't check the TaskQuerySqlProvider yet. I will do that soon :)

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java [hunk 12]
```diff
@@ -0,0 +1,264 @@
...
+            .objectReferences(sor2)
+            .due(Instant.parse("2022-11-10T09:45:00.000Z"))
+            .name("Name2")
+            .attachments(
+                TaskAttachmentBuilder.newAttachment()
+                    .channel("A")
+                    .classificationSummary(defaultClassificationSummary)
+                    .objectReference(por2)
+                    .build())
+            .buildAndStoreAsSummary(taskService);
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java:77]: It's because of the due date, as Tasks are sorted by due date in this test by default. It was important to add Tasks in a different order than their due dates to check if they really get sorted.  So the 1, 2, 3 numbers refer to the order that the Tasks will have after they have been sorted. I'm not sure if it's better the other way round.

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java [hunk 13]
```diff
@@ -0,0 +1,264 @@
...
+  @Test
+  void should_GroupByPor_When_OrderingByName() {
+    List<TaskSummary> list =
+        taskService
+            .createTaskQuery()
+            .workbasketIdIn(defaultWorkbasket.getId())
+            .groupByPor()
+            .orderByName(SortDirection.ASCENDING)
+            .list();
+    assertThat(list).isNotEmpty().hasSize(1);
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java:149]: Ok

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java [hunk 14]
```diff
@@ -0,0 +1,264 @@
...
+import pro.taskana.testapi.builder.TaskAttachmentBuilder;
+import pro.taskana.testapi.builder.TaskBuilder;
+import pro.taskana.testapi.builder.WorkbasketAccessItemBuilder;
+import pro.taskana.testapi.security.WithAccessId;
+import pro.taskana.workbasket.api.WorkbasketPermission;
+import pro.taskana.workbasket.api.WorkbasketService;
+import pro.taskana.workbasket.api.models.WorkbasketSummary;
+
+@TaskanaIntegrationTest
+@DisabledIfEnvironmentVariable(named = "DB", matches = "ORACLE")
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java:34]: - Yes, this will be resolved in the future
- We don't, but I can add it

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java [hunk 15]
```diff
@@ -0,0 +1,264 @@
...
+            .workbasketIdIn(defaultWorkbasket.getId())
+            .groupByPor()
+            .orderByName(SortDirection.ASCENDING)
+            .list();
+    assertThat(list).isNotEmpty().hasSize(1);
+    assertThat(list.get(0))
+        .usingRecursiveComparison()
+        .ignoringFields("groupByCount")
+        .isEqualTo(taskSummary3);
+    assertThat(list.get(0).getGroupByCount()).isEqualTo(3);
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java:154]: Ok :) I still need the get(0) when comparing groupByCount

File: lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java [hunk 16]
```diff
@@ -289,6 +289,8 @@ void should_PopulateEveryTaskanaConfiguration_When_EveryBuilderFunctionIsCalled(
       boolean expectedAddAdditionalUserInfo = true;
       Set<WorkbasketPermission> expectedMinimalPermissionsToAssignDomains =
           Set.of(WorkbasketPermission.CUSTOM_2);
+      // database configuration
+      boolean expecteduseSpecificDb2Taskquery = false;
```
Comment (gitgoodjhe) [inline lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java:293]: Should we maybe make the "u" in "use" a capital letter to follow camelCase?

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java [hunk 17]
```diff
@@ -1217,6 +1217,29 @@ public interface TaskQuery extends BaseQuery<TaskSummary, TaskQueryColumnName> {
    */
   TaskQuery orderByPrimaryObjectReferenceValue(SortDirection sortDirection);
 
+  // endregion
+  // region groupBy
+
+  /**
+   * Group the {@linkplain Task Tasks} that will be returned by this query according the value of
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1224]:
```suggestion
   * Group the {@linkplain Task Tasks} that will be returned by this query according to the value of
```

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java [hunk 18]
```diff
@@ -1217,6 +1217,29 @@ public interface TaskQuery extends BaseQuery<TaskSummary, TaskQueryColumnName> {
...
+   * their {@linkplain Task#getPrimaryObjRef() primary ObjectReference}. Only one Task will be
+   * returned for all Tasks with the same value.
+   *
+   * @return the query
+   */
+  TaskQuery groupByPor();
+
+  /**
+   * Group the {@linkplain Task Tasks} that will be returned by this query according the value of
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1233]:
```suggestion
   * Group the {@linkplain Task Tasks} that will be returned by this query according to the value of
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 19]
```diff
@@ -57,8 +64,10 @@ public static String queryTaskSummaries() {
         + commonTaskWhereStatement()
         + "<if test='selectAndClaim == true'> AND t.STATE = 'READY' </if>"
         + CLOSING_WHERE_TAG
-        + "<if test='!orderBy.isEmpty()'>"
-        + "ORDER BY <foreach item='item' collection='orderBy' separator=',' >${item}</foreach>"
+        + closeOuterClauseForAggregatingByPor()
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:67]:
```suggestion
        + closeOuterClauseForGroupByPor()
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 20]
```diff
@@ -57,8 +64,10 @@ public static String queryTaskSummaries() {
...
+        + closeOuterClauseForAggregatingBySor()
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:68]:
```suggestion
        + closeOuterClauseForGroupBySor()
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 21]
```diff
@@ -216,6 +233,8 @@ public static String countQueryTasks() {
         + checkForAuthorization()
         + commonTaskWhereStatement()
         + CLOSING_WHERE_TAG
+        + closeOuterClauseForAggregatingByPor()
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:236]:
```suggestion
        + closeOuterClauseFoGroupByPor()
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 22]
```diff
@@ -216,6 +233,8 @@ public static String countQueryTasks() {
...
+        + closeOuterClauseForAggregatingBySor()
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:237]:
```suggestion
        + closeOuterClauseForGroupBySor()
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 23]
```diff
@@ -379,6 +398,106 @@ private static String checkForAuthorization() {
...
+        + "</if> "
+        + "<if test='orderByInner.isEmpty()'>"
+        + "ORDER BY DUE"
+        + "</if> "
+        + ")"
+        + "AS rn"
+        + "</if> ";
+  }
+
+  private static String openOuterClauseForAggregatingByPorOrSor() {
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:431]:
```suggestion
  private static String openOuterClauseForGroupByPorOrSor() {
```

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 24]
```diff
@@ -379,6 +398,106 @@ private static String checkForAuthorization() {
...
+    return "<if test=\"groupByPor or groupBySor != null\"> "
+        + "SELECT * FROM ("
+        + "</if> ";
+  }
+
+  private static String closeOuterClauseForAggregatingByPor() {
```
Comment (gitgoodjhe) [inline lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:437]:
```suggestion
  private static String closeOuterClauseForGroupByPor() {
```

**Review by gitgoodjhe — CHANGES_REQUESTED** [review]

File: lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java (hunk 16 above)
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java:293]: Sounds good :)

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java (hunk 17 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1224]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java (hunk 18 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java:1233]: Ok :)

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java (hunk 19 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:67]: Ok :)

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java (hunk 20 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:68]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java (hunk 22 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:237]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java (hunk 23 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:431]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java (hunk 24 above)
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:437]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java [hunk 25]
```diff
@@ -379,6 +398,106 @@ private static String checkForAuthorization() {
...
+        + checkForAuthorization()
+        + commonTaskWhereStatement()
+        + "<if test='selectAndClaim == true'> AND t.STATE = 'READY' </if>"
+        + CLOSING_WHERE_TAG
+        + "GROUP BY POR_VALUE) AS tt ON t.POR_VALUE=tt.PVALUE "
+        + "WHERE rn = 1"
+        + "</if> ";
+  }
+
+  private static String closeOuterClauseForAggregatingBySor() {
```
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java:470]: Ok

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:72]: We don't have this annotation for other fields, even the "unused" ones. It would be more consistent not to add it. What do you think about it?

File: lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (ryzheboka) [reply lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java:73]: We don't have this annotation for other fields, even the "unused" ones. It would be more consistent not to add it. What do you think about it?

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java [hunk 26]
```diff
@@ -0,0 +1,334 @@
...
+import pro.taskana.testapi.builder.WorkbasketAccessItemBuilder;
+import pro.taskana.testapi.security.WithAccessId;
+import pro.taskana.user.api.UserService;
+import pro.taskana.workbasket.api.WorkbasketPermission;
+import pro.taskana.workbasket.api.WorkbasketService;
+import pro.taskana.workbasket.api.models.WorkbasketSummary;
+
+@TaskanaIntegrationTest
+@DisabledIfEnvironmentVariable(named = "DB", matches = "ORACLE")
+public class TaskQueryImplGroupByAccTest implements TaskanaConfigurationModifier {
```
Comment (mustaphazorgati) [inline lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java:37]:
```suggestion
class TaskQueryImplGroupByAccTest implements TaskanaConfigurationModifier {
```
fixes a code smell :)

**Review by gitgoodjhe — DISMISSED** [review]

**Review by mustaphazorgati — APPROVED** [review]

File: lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java (hunk 26 above)
Comment (ryzheboka) [reply lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java]: Ok :) I fixed it

**Comment by ryzheboka** [comment]
Thanks for the reviews! @arolfes could you approve the PR or request new changes?
